{
 "title": "Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "JStressy Scenario Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Echo WebSocket Connections Current",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "echo_websockets" }
   ]
  },
  {
   "title": "Echo WebSocket Connections Average",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "echo_websockets" }
   ]
  },
  {
   "title": "Echo WebSocket Connections Max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "echo_websockets" }
   ]
  },
  {
   "title": "Echo WebSocket Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "echo_websockets" }
   ]
  },
  { "title": "JStressy Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Threads Live",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{job=\"stressy\"}"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"stressy\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", job=\"stressy\"}"
    }
   ]
  },
  {
   "title": "VertX Open WebSocket Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_metrics_http_client__open_websockets"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds{job=\"stressy\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"stressy\"}"
    }
   ]
  },
  {
   "title": "JVM Buffer Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count{job=\"stressy\"}"
    }
   ]
  },
  {
   "title": "VertX Queue Delay",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_metrics_http_client_echo_websocket_org:443_queue_delay_seconds"
    }
   ]
  }
 ]
}