version: '3'

services:
  stressy:
    build:
      context: ./stressy
    image: stressy:latest
    container_name: stressy
    volumes:
      - ./stressy-conf:/etc/stressy
      - /var/log/stressy:/logs
    ports:
      - 9089:8089
      - 9000:8000
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '20'
    links:
      - stressy-prometheus
      - stressy-grafana
    restart: unless-stopped
    networks:
      - stress-test
  stressy-http-echo:
    build:
      context: ./stressy-http-echo
    image: stressy-http-echo:latest
    container_name: stressy-http-echo
    volumes:
      - /var/log/stressy-http-echo:/logs
    ports:
      - 8082:8082
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '20'
    links:
      - stressy
    restart: unless-stopped
    networks:
      - stress-test
  stressy-http-websocket:
    build:
      context: ./stressy-websocket-echo
    image: stressy-websocket-echo:latest
    container_name: stressy-websocket-echo
    volumes:
      - /var/log/websocket-echo:/logs
    ports:
      - 8081:8081
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '20'
    links:
      - stressy
    restart: unless-stopped
    networks:
      - stress-test
  stressy-prometheus:
    image: prom/prometheus:v2.2.1
    container_name: stressy-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=1w'
    ports:
      - 9092:9090
    restart: unless-stopped
    networks:
      - stress-test
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '20'
  stressy-grafana:
    image: grafana/grafana:10.1.2
    container_name: stressy-grafana
    volumes:
      - ./grafana:/etc/grafana
    ports:
      - 3002:3000
    links:
      - stressy-prometheus
    environment:
      GF_RENDERING_SERVER_URL: http://stressy-grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://stressy-grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - stress-test
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '20'
    restart: unless-stopped
  stressy-grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: stressy-grafana-renderer
    ports:
      - 8081
    links:
      - stressy-grafana
    networks:
      - stress-test
networks:
  stress-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/12