/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 Denis Timofeev <timofeevda@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 *
 */

package com.github.timofeevda.jstressy.plugin.core;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Collection;
import java.util.Properties;

/**
 * Felix configuration writer
 *
 * @author timofeevda
 */
public class FelixConfigWriter {

    private static final String COMMENT_STRING = "Apache Felix Configuration File. \n" +
            "This file was auto-generated by JStressy Package Plugin.\n";

    public static void writeConfig(String configTemplate,
                                   String targetFolder) throws IOException {
        Properties properties = createFelixProperties(configTemplate);

        try (FileOutputStream propsFos = new FileOutputStream(
                new File(targetFolder + File.separator + Constants.PATH_TO_FELIX_PROPERTIES))) {
            properties.store(propsFos, COMMENT_STRING);
        }
    }

    private static Properties createFelixProperties(String configTemplate) throws IOException {
        Properties properties = new Properties();

        // load properties from template
        try (FileInputStream propsFis = new FileInputStream(
                new File(configTemplate + File.separator + Constants.PATH_TO_FELIX_PROPERTIES))) {
            properties.load(propsFis);
        }
        return properties;
    }

}

